name: Testes Automatizados

on:
  push:
    branches:
      - Testes_Unitarios  # O workflow será acionado em commits na branch "Testes_Unitarios"
  pull_request:
    branches:
      - Testes_Unitarios  # Também rodará ao abrir PRs

jobs:
  test:
    runs-on: ubuntu-latest  # Define o sistema operacional da máquina virtual
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt || echo "Nenhum arquivo de dependências encontrado"

      - name: Rodar testes unitários
        run: python -m unittest discover tests
